# Generated by Django 4.0 on 2023-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject1',
            new_name='subject_1',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject2',
            new_name='subject_2',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject3',
            new_name='subject_3',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject4',
            new_name='subject_4',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject5',
            new_name='subject_5',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject6',
            new_name='subject_6',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject7',
            new_name='subject_7',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject8',
            new_name='subject_8',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='subject9',
            new_name='subject_9',
        ),
    ]
