# Generated by Django 4.0 on 2023-04-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_subject1_marksheet_subject_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='examination_date',
        ),
    ]
