# Generated by Django 4.0 on 2023-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_marksheet_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='dob',
            field=models.DateField(default='2002-02-22'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='examination_date',
            field=models.DateField(default='2002-08-12'),
        ),
    ]
