# Generated by Django 4.0 on 2023-04-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_marksheet_dob_marksheet_examination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='marksheet_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='markSheetCode',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
