# Generated by Django 4.0 on 2023-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_marksheet_marksheet_id_alter_marksheet_marksheetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='report_card',
            field=models.FileField(upload_to='pdf_files'),
        ),
    ]
