# Generated by Django 4.0 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_marksheet_report_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='report_card',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='pdf_files/'),
        ),
    ]
