# Generated by Django 4.2.1 on 2023-05-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_schooldetail_studentdetail_marksheetformat2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarksheetFormat2',
            new_name='MarksheetFormat_2',
        ),
        migrations.CreateModel(
            name='MarksheetFormat_3',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('marksheet_id', models.CharField(default='', max_length=20)),
                ('total_grade', models.CharField(max_length=3)),
                ('hindi', models.PositiveSmallIntegerField()),
                ('english', models.PositiveSmallIntegerField()),
                ('science', models.PositiveSmallIntegerField()),
                ('social_science', models.PositiveSmallIntegerField()),
                ('maths', models.PositiveSmallIntegerField()),
                ('sanskrit', models.PositiveSmallIntegerField()),
                ('work_education', models.PositiveSmallIntegerField()),
                ('physical', models.PositiveSmallIntegerField()),
                ('arts', models.PositiveSmallIntegerField()),
                ('examination_year', models.DateField()),
                ('report_card', models.FileField(default=None, max_length=255, null=True, upload_to='pdf_files/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentdetail')),
            ],
        ),
    ]
