# Generated by Django 4.2.1 on 2023-05-16 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_marksheetformat2_marksheetformat_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksheetFormat_1',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('marksheet_id', models.CharField(default='', max_length=20)),
                ('total_grade', models.CharField(max_length=3)),
                ('examination_date', models.DateField()),
                ('report_card', models.FileField(default=None, max_length=255, null=True, upload_to='pdf_files/')),
                ('subject_1', models.CharField(max_length=5)),
                ('subject_2', models.CharField(max_length=5)),
                ('subject_3', models.CharField(max_length=5)),
                ('subject_4', models.CharField(max_length=5)),
                ('subject_5', models.CharField(max_length=5)),
                ('subject_6', models.CharField(max_length=5)),
                ('subject_7', models.CharField(max_length=5)),
                ('subject_8', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Marksheet',
        ),
        migrations.RenameField(
            model_name='marksheetformat_2',
            old_name='examination_year',
            new_name='examination_date',
        ),
        migrations.RenameField(
            model_name='marksheetformat_3',
            old_name='total_grade',
            new_name='arts_100',
        ),
        migrations.RenameField(
            model_name='marksheetformat_3',
            old_name='examination_year',
            new_name='examination_date',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='arts',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='english',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='hindi',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='maths',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='physical',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='sanskrit',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='science',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='social_science',
        ),
        migrations.RemoveField(
            model_name='marksheetformat_3',
            name='work_education',
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='arts_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='arts_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='english_100',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='english_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='english_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='hindi_100',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='hindi_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='hindi_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='maths_100',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='maths_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='maths_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='percentage',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='physical_100',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='physical_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='physical_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='result',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='sanskrit_100',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='sanskrit_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='sanskrit_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='science_100',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='science_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='science_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='shreni',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='social_science_100',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='social_science_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='social_science_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='work_education_100',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='work_education_20',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheetformat_3',
            name='work_education_80',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='examination_center_code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='student_class',
            field=models.CharField(default=8, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='swayam_pathi',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='arts',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='english',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='hindi',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='maths',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='physical',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='sanskrit',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='science',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='social_science',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='marksheetformat_2',
            name='work_education',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='marksheetformat_1',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentdetail'),
        ),
    ]
