# Generated by Django 4.2.1 on 2023-05-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_schooldetail_examination_center_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksheetformat_1',
            old_name='subject_1',
            new_name='arts',
        ),
        migrations.RenameField(
            model_name='marksheetformat_1',
            old_name='subject_2',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='marksheetformat_1',
            old_name='subject_3',
            new_name='environmental_studies',
        ),
        migrations.RenameField(
            model_name='marksheetformat_1',
            old_name='subject_4',
            new_name='hindi',
        ),
        migrations.RenameField(
            model_name='marksheetformat_1',
            old_name='subject_5',
            new_name='maths',
        ),
        migrations.RenameField(
            model_name='marksheetformat_1',
            old_name='subject_6',
            new_name='physical',
        ),
        migrations.RenameField(
            model_name='marksheetformat_1',
            old_name='subject_7',
            new_name='sanskrit',
        ),
        migrations.RenameField(
            model_name='marksheetformat_1',
            old_name='subject_8',
            new_name='working_education',
        ),
    ]
