# Generated by Django 4.2.1 on 2023-05-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_subject_1_marksheetformat_1_arts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooldetail',
            old_name='kendra_code',
            new_name='examination_center_code',
        ),
    ]
